name: Generar PPT desde slides.md

on:
  workflow_dispatch:

jobs:
  generar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar dependencias
        run: |
          pip install python-pptx

      - name: Generar PPTX
        run: |
          python scripts/generate_ppt_md.py

      - name: Subir artefacto (presentacion.pptx)
        uses: actions/upload-artifact@v4
        with:
          name: presentacion
          path: presentacion.pptx